build:
  maxIssues: 0

complexity:
  CyclomaticComplexMethod:
    active: true
    threshold: 30
  LongMethod:
    active: true
    threshold: 180
  LongParameterList:
    active: true
    functionThreshold: 8
    constructorThreshold: 10
    ignoreDefaultParameters: true
  TooManyFunctions:
    active: true
    thresholdInFiles: 30
    thresholdInClasses: 25
    thresholdInInterfaces: 20
    thresholdInObjects: 20
    thresholdInEnums: 20

naming:
  FunctionNaming:
    active: true
    ignoreAnnotated:
      - Composable
  MatchingDeclarationName:
    active: false

style:
  MagicNumber:
    active: false
  MaxLineLength:
    active: false
